services:
  cy-mysql8:
    container_name: cy-mysql8
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      设置初始化脚本
      - ./mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      注意这里我映射为了 13316 端口
      - "13316:3306"
  cy-redis:
    container_name: cy-redis
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - '6379:6379'
  cy-postgres:
    container_name: cy-postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "@Abcd123456"
      POSTGRES_USER:  postgres
      POSTGRES_DB: kratos_monolithic
      TZ: Asia/Shanghai
    ports:
      - 5432:5432
    restart: always